config:
  info: dev version:1

spring:
  application:
    name: cloud-config-client
  cloud:
    config:
      label: main   # 分支名称
      name: config  # 配置文件名称
      profile: dev  # 后缀名 上述3个综合：main分支上config-dev.yml的配置文件被读取  http://config3344.com:3344/main/config-dev.yml
      uri: http://config3344.com:3344
  #rabbitmq整合
  rabbitmq:
    host: 81.69.59.69
    port: 5672
    username: test
    password: test


eureka:
  client:
    # 注册进eureka
    register-with-eureka: true
    # 是否从eureka注册中心抓取已有的注册信息 集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露监控端点  最新配置还是需要手动刷新，需要手动发post请求，比如刷新本项目的配置文件，发post请求：curl -X POST "http://localhost:3355/actuator/refresh"
management:
  endpoints:
    web:
      exposure:
        include: "*"